image: registry.gitlab.com/alienspaces/flutter-bloc-card-flip/cirrusci/flutter:stable

stages:
  - test
  - build

test-app:
  stage: test
  image: registry.gitlab.com/alienspaces/flutter-bloc-card-flip/cirrusci/flutter:stable
  script:
    - flutter test

build-app:
  stage: build
  image: registry.gitlab.com/alienspaces/flutter-bloc-card-flip/cirrusci/flutter:stable
  script:
    - git checkout master
    - script/build-update-web
    - git push
  only:
    - master
