#!/usr/bin/env bash

# This scripts builds a web version of the application and 
# updates the `docs` directory with the result.
flutter channel stable

# Build the web version
flutter build web

# Copy into the Github pages location
cp -r build/web/* ./docs

# Git add and commit
git add .
git status
git commit -m "Updated web build"
