#!/usr/bin/env bash

# Build the web version
flutter build web

# Copy into the Github pages location
cp -r build/web/* ./docs

# Git add and commit
git add .
git status
git commit -m "Updated web build"
